version: "3.9"
services:
  nvim:
    # image: ph-nvim
    build: .
    volumes:
      - nvim_home:/root/.local
      - nvim_projects:/projects
    tty: true
volumes:
  nvim_home:
    name: nvim_home
  nvim_projects:
    name: nvim_projects
