version: "3.9"
services:
  nvim:
    image: pedrohms/nvim-nightly
    volumes:
      - ~/.config/nvim:/root/.config/nvim
      - ~/.local/share/nvim:/root/.local/share/nvim
      - ~/Projects:/Projects
    tty: true
